#List example in Python
fruits = ("Apple", "Grapes", "Coconut", "Mango", "Pineapple", "Jackfruit", "Papaya")
print(fruits)
print(fruits[0:4:2])
print(fruits[2::2])
print(fruits[::-1])
city = ("Patna", "Patliputra", "Samastipur", "Motihari", "Dhaka", "Rampur", "Utter Pradesh", "Madhya Pradesh")
print(city)
print(city[::])
print(city[0:10:2])
print(city[::-1])
name = ("Rajan Kumar", "Sonu Kumar", "Anjani Kumar", "Anjali Kumari", "Sunny Kumar", "Krishnandan Kumar", "Chanchal Kumar")
print(name[0:9])
print(name[::-1])
